spring:
  redis:
    password: 113536
    host: zzw-redis
  rabbitmq:
    host: zzw-rabbitmq
    port: 5672
    username: zhangzhiwen
    password: 113536
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zhangzhiwen
    password: 113536
    url: jdbc:mysql://zzw-mysql:3306/sell?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
